import * as fs from "node:fs";
import { parse as parseYaml } from "yaml";
import { describe, expect, it } from "vitest";
import { validateAgainstSchema } from "../runtime/commands/shared.js";
import {
  buildMacOSStudioContractFixture,
  MACOS_STUDIO_CONTRACT_FIXTURE_PATH,
  serializeMacOSStudioContractFixture,
} from "../scripts/generate-macos-studio-contract-fixture.js";

interface StudioContractFixture {
  artifactVersion: string;
  playbackCases: Array<{ id: string; expected: { state: string } }>;
  preflightCases: Array<{
    id: string;
    files: Record<string, string>;
    expected: { ok: boolean; issues: string[] };
  }>;
  packageCases: Array<{
    id: string;
    files: Record<string, string>;
    expected: {
      ready: boolean;
      readinessLabel: string;
      issues: string[];
    };
  }>;
}

describe("macOS Studio cross-language contract fixture", () => {
  it("is generated byte-for-byte from live TypeScript oracles", () => {
    expect(fs.readFileSync(MACOS_STUDIO_CONTRACT_FIXTURE_PATH, "utf8"))
      .toBe(serializeMacOSStudioContractFixture());
  }, 30_000);

  it("covers playback, hidden Gate 10 freshness, and package failure modes", () => {
    const fixture = buildMacOSStudioContractFixture() as StudioContractFixture;

    expect(fixture.artifactVersion).toBe("macos-studio-contract/v1");
    expect(fixture.playbackCases.map((testCase) => testCase.expected.state)).toEqual([
      "missing_timeline",
      "missing_manifest",
      "legacy_manifest",
      "exact",
      "stale",
    ]);
    expect(fixture.preflightCases.find((testCase) => testCase.id === "ready_engine_render")?.expected.ok)
      .toBe(true);
    expect(fixture.preflightCases.find((testCase) => testCase.id === "missing_approval")?.expected.issues)
      .toContain("approval_record is missing");
    expect(fixture.preflightCases.find((testCase) => testCase.id === "stale_caption_approval")?.expected.issues)
      .toContain("caption_approval is stale");
    expect(Object.fromEntries(fixture.packageCases.map((testCase) => [
      testCase.id,
      testCase.expected.readinessLabel,
    ]))).toEqual({
      valid: "render packaged",
      qa_missing_details: "qa report unreadable",
      qa_unknown_property: "qa report unreadable",
      manifest_missing_provenance: "package manifest unreadable",
      manifest_unknown_property: "package manifest unreadable",
      qa_profile_mismatch: "package contract mismatch",
      project_id_mismatch: "package contract mismatch",
      source_of_truth_mismatch: "package contract mismatch",
      final_hash_mismatch: "package contract mismatch",
      qa_hash_mismatch: "package contract mismatch",
      timeline_hash_mismatch: "package contract mismatch",
      packaging_projection_mismatch: "package contract mismatch",
      packaging_projection_input_changed: "package contract mismatch",
      qa_passed_with_failed_check: "qa failed",
      qa_empty_checks: "qa failed",
      timeline_version_mismatch: "package contract mismatch",
      source_inputs_provenance_missing: "package manifest unreadable",
      state_unknown_property: "package contract mismatch",
    });
    expect(fixture.packageCases.find((testCase) => testCase.id === "valid")?.expected.ready).toBe(true);
    expect(fixture.packageCases.filter((testCase) => testCase.id !== "valid").every((testCase) => !testCase.expected.ready))
      .toBe(true);
  }, 30_000);

  it("uses schema-valid canonical artifacts for every Gate 10 fixture", () => {
    const fixture = buildMacOSStudioContractFixture() as StudioContractFixture;

    for (const testCase of fixture.preflightCases) {
      expect(validateAgainstSchema(
        JSON.parse(testCase.files["05_timeline/timeline.json"]),
        "timeline-ir.schema.json",
      ), testCase.id).toMatchObject({ valid: true });
      expect(validateAgainstSchema(
        parseYaml(testCase.files["06_review/review_report.yaml"]),
        "review-report.schema.json",
      ), testCase.id).toMatchObject({ valid: true });
    }
    for (const testCase of fixture.packageCases) {
      expect(validateAgainstSchema(
        JSON.parse(testCase.files["02_media/source_map.json"]),
        "source-map.schema.json",
      ), testCase.id).toMatchObject({ valid: true });
    }
  }, 30_000);
});
