import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { parse as parseYaml } from "yaml";
import { describe, expect, it } from "vitest";
import { validateAgainstSchema } from "../runtime/commands/shared.js";
import {
  buildMacOSStudioContractFixture,
  MACOS_STUDIO_CONTRACT_FIXTURE_PATH,
  serializeMacOSStudioContractFixture,
} from "../scripts/generate-macos-studio-contract-fixture.js";
import {
  MACOS_STUDIO_FIXTURE_RENDERER_IDENTITY,
} from "../scripts/helpers/macos-studio-fixture-renderer-versions.js";

interface StudioContractFixture {
  artifactVersion: string;
  playbackCases: Array<{ id: string; expected: { state: string } }>;
  preflightCases: Array<{
    id: string;
    files: Record<string, string>;
    expected: {
      ok: boolean;
      decision: string;
      issues: string[];
      project_identity: { status: string; project_id?: string };
      structured_issues: Array<{ code: string; message: string }>;
    };
  }>;
  preflightProcessCases: Array<{
    id: string;
    exitCode: number;
    stdout: string;
    expected: { available: boolean; canPackage: boolean; failureLabel?: string };
  }>;
  packageCases: Array<{
    id: string;
    files: Record<string, string>;
    expected: {
      ready: boolean;
      readinessLabel: string;
      issues: string[];
    };
  }>;
}

describe("macOS Studio cross-language contract fixture", () => {
  it("is generated byte-for-byte from live TypeScript oracles", () => {
    expect(fs.readFileSync(MACOS_STUDIO_CONTRACT_FIXTURE_PATH, "utf8"))
      .toBe(serializeMacOSStudioContractFixture());
  }, 30_000);

  it("is byte-for-byte independent of the host FFmpeg identity", () => {
    const baseline = serializeMacOSStudioContractFixture();
    const fakeBin = fs.mkdtempSync(path.join(os.tmpdir(), "studio-contract-fake-ffmpeg-"));
    const fakeFfmpeg = path.join(fakeBin, "ffmpeg");
    fs.writeFileSync(
      fakeFfmpeg,
      "#!/bin/sh\necho 'ffmpeg version forged-host-version'\n",
      "utf8",
    );
    fs.chmodSync(fakeFfmpeg, 0o755);
    const previousPath = process.env.PATH;
    process.env.PATH = `${fakeBin}${path.delimiter}${previousPath ?? ""}`;
    try {
      const alternateHost = serializeMacOSStudioContractFixture();
      expect(alternateHost).toBe(baseline);
      expect(alternateHost).toContain(MACOS_STUDIO_FIXTURE_RENDERER_IDENTITY.ffmpeg);
      expect(alternateHost).not.toContain("forged-host-version");
    } finally {
      if (previousPath === undefined) delete process.env.PATH;
      else process.env.PATH = previousPath;
      fs.rmSync(fakeBin, { recursive: true, force: true });
    }
  }, 30_000);

  it("covers playback, hidden Gate 10 freshness, and package failure modes", () => {
    const fixture = buildMacOSStudioContractFixture() as StudioContractFixture;

    expect(fixture.artifactVersion).toBe("macos-studio-contract/v1");
    expect(fixture.playbackCases.map((testCase) => testCase.expected.state)).toEqual([
      "missing_timeline",
      "missing_manifest",
      "legacy_manifest",
      "exact",
      "stale",
    ]);
    expect(fixture.preflightCases.find((testCase) => testCase.id === "ready_engine_render")?.expected.ok)
      .toBe(true);
    expect(fixture.preflightCases.find((testCase) => testCase.id === "ready_engine_render")?.expected)
      .toMatchObject({
        decision: "ready_to_run",
        project_identity: { status: "confirmed", project_id: "studio-contract" },
        structured_issues: [],
      });
    expect(fixture.preflightCases.find((testCase) => testCase.id === "empty_id_inferred")?.expected)
      .toMatchObject({
        ok: true,
        decision: "ready_to_run",
        project_identity: { status: "inferred", project_id: "studio-contract" },
      });
    expect(fixture.preflightCases.find((testCase) => testCase.id === "project_id_mismatch")?.expected)
      .toMatchObject({
        ok: false,
        decision: "blocked",
        project_identity: { status: "conflict" },
        structured_issues: [{ code: "PACKAGE_PREFLIGHT_PROJECT_ID_MISMATCH" }],
      });
    expect(fixture.preflightCases.find((testCase) => testCase.id === "malformed_identity_artifact")?.expected.structured_issues)
      .toContainEqual(expect.objectContaining({ code: "PACKAGE_PREFLIGHT_IDENTITY_ARTIFACT_MALFORMED" }));
    expect(fixture.preflightCases.find((testCase) => testCase.id === "missing_approval")?.expected.issues)
      .toContain("approval_record is missing");
    expect(fixture.preflightCases.find((testCase) => testCase.id === "stale_caption_approval")?.expected.issues)
      .toContain("caption_approval is stale");
    expect(fixture.preflightCases.find((testCase) => testCase.id === "missing_final_render_approval")?.expected)
      .toMatchObject({
        ok: false,
        decision: "blocked",
        structured_issues: [{ code: "PACKAGE_PREFLIGHT_FINAL_RENDER_APPROVAL_MISSING" }],
      });
    expect(Object.fromEntries(fixture.packageCases.map((testCase) => [
      testCase.id,
      testCase.expected.readinessLabel,
    ]))).toEqual({
      valid: "render packaged",
      valid_captioned: "render packaged",
      qa_missing_details: "qa report unreadable",
      qa_unknown_property: "qa report unreadable",
      manifest_missing_provenance: "package manifest unreadable",
      manifest_unknown_property: "package manifest unreadable",
      qa_profile_mismatch: "package contract mismatch",
      project_id_mismatch: "package contract mismatch",
      source_of_truth_mismatch: "package contract mismatch",
      final_hash_mismatch: "package contract mismatch",
      qa_hash_mismatch: "package contract mismatch",
      timeline_hash_mismatch: "package contract mismatch",
      packaging_projection_mismatch: "package contract mismatch",
      packaging_projection_input_changed: "package contract mismatch",
      qa_passed_with_failed_check: "qa failed",
      qa_empty_checks: "qa failed",
      timeline_version_mismatch: "package contract mismatch",
      source_inputs_provenance_missing: "package manifest unreadable",
      state_unknown_property: "package contract mismatch",
      render_route_receipt_tampered: "package contract mismatch",
      render_route_drift: "package contract mismatch",
      renderer_version_drift: "package contract mismatch",
      encode_pass_drift: "package contract mismatch",
      font_receipt_missing: "package contract mismatch",
      font_receipt_tampered: "package contract mismatch",
      layer_receipt_missing: "package contract mismatch",
    });
    expect(fixture.packageCases.find((testCase) => testCase.id === "valid")?.expected.ready).toBe(true);
    expect(fixture.packageCases.find((testCase) => testCase.id === "valid_captioned")?.expected.ready)
      .toBe(true);
    expect(fixture.packageCases.filter((testCase) =>
      !["valid", "valid_captioned"].includes(testCase.id)
    ).every((testCase) => !testCase.expected.ready))
      .toBe(true);
    expect(fixture.preflightProcessCases.map((testCase) => testCase.id)).toEqual([
      "normal",
      "empty_id_inferred",
      "project_id_mismatch",
      "malformed_json",
      "exit_json_contradiction",
    ]);
    expect(fixture.preflightProcessCases.find((testCase) => testCase.id === "exit_json_contradiction")?.expected)
      .toEqual({
        available: false,
        canPackage: false,
        failureLabel: "package preflight unavailable",
      });
  }, 30_000);

  it("uses schema-valid canonical artifacts for every Gate 10 fixture", () => {
    const fixture = buildMacOSStudioContractFixture() as StudioContractFixture;

    for (const testCase of fixture.preflightCases) {
      expect(validateAgainstSchema(
        JSON.parse(testCase.files["05_timeline/timeline.json"]),
        "timeline-ir.schema.json",
      ), testCase.id).toMatchObject({ valid: true });
      expect(validateAgainstSchema(
        parseYaml(testCase.files["06_review/review_report.yaml"]),
        "review-report.schema.json",
      ), testCase.id).toMatchObject({ valid: true });
    }
    for (const testCase of fixture.packageCases) {
      expect(validateAgainstSchema(
        JSON.parse(testCase.files["02_media/source_map.json"]),
        "source-map.schema.json",
      ), testCase.id).toMatchObject({ valid: true });
    }
  }, 30_000);
});
